# Generated by Django 2.1.2 on 2018-11-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181010_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='conteudo',
            field=models.TextField(verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nomeUsuario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nome'),
        ),
    ]
